



const auth = 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE2ZTVmZDk3LTBkY2ItMTFlOS04YmIwLTAyNDJhYzEyMDAwMyIsImlhdCI6MTU0NjUyOTMwMywiZXhwIjoxNTQ2NjE1NzAzfQ.gpnVzEULV7QyYDCT22a7fJ00pOa9Jv_YqB-fl_iRaSg';
export default auth